import { Game, Friend, User, Badge } from "./types";

export const badges: Badge[] = [
  { id: "b1", name: "Early Adopter", icon: "🌟", description: "Joined HNPP GAME early" },
  { id: "b2", name: "Social Butterfly", icon: "🦋", description: "Made 10+ friends" },
  { id: "b3", name: "Game Master", icon: "🎮", description: "Played 50+ games" },
  { id: "b4", name: "Creator", icon: "🛠️", description: "Uploaded first game" },
  { id: "b5", name: "Champion", icon: "🏆", description: "Won 10 matches" },
];

export const currentUser: User = {
  id: "u1",
  username: "HNPP_Player",
  avatar: "/avatars/default.png",
  level: 12,
  xp: 2400,
  xpToNext: 3000,
  gamesPlayed: 47,
  friends: 23,
  joinDate: "2024-01-15",
  bio: "Welcome to HNPP GAME! Ready to play!",
  badges: [badges[0], badges[2], badges[4]],
};

export const games: Game[] = [
  {
    id: "g1",
    title: "HNPP Obby Challenge",
    description: "Navigate through challenging obstacle courses! Jump, climb, and dodge your way to victory in this classic obby experience.",
    thumbnail: "obby",
    category: "Adventure",
    players: 1247,
    maxPlayers: 50,
    rating: 4.8,
    creator: "HNPP_Studio",
    tags: ["obby", "parkour", "challenge"],
    featured: true,
  },
  {
    id: "g2",
    title: "Tower Defense Legends",
    description: "Build towers and defend your base from waves of enemies. Upgrade your defenses and unlock powerful abilities!",
    thumbnail: "tower",
    category: "Strategy",
    players: 892,
    maxPlayers: 4,
    rating: 4.5,
    creator: "TDMaster",
    tags: ["tower-defense", "strategy", "multiplayer"],
    featured: true,
  },
  {
    id: "g3",
    title: "Speed Race X",
    description: "High-speed racing with customizable vehicles. Race against friends on epic tracks!",
    thumbnail: "racing",
    category: "Racing",
    players: 2103,
    maxPlayers: 12,
    rating: 4.7,
    creator: "SpeedKing",
    tags: ["racing", "cars", "multiplayer"],
    featured: true,
  },
  {
    id: "g4",
    title: "Zombie Survival",
    description: "Survive waves of zombies with your team. Collect weapons, build fortifications, and stay alive!",
    thumbnail: "zombie",
    category: "Action",
    players: 3456,
    maxPlayers: 20,
    rating: 4.9,
    creator: "ZombieHunter",
    tags: ["survival", "zombie", "action", "coop"],
  },
  {
    id: "g5",
    title: "Tycoon Empire",
    description: "Build your business empire from scratch. Manage resources, hire workers, and become the richest tycoon!",
    thumbnail: "tycoon",
    category: "Simulation",
    players: 1567,
    maxPlayers: 30,
    rating: 4.3,
    creator: "BizBuilder",
    tags: ["tycoon", "business", "simulation"],
  },
  {
    id: "g6",
    title: "Battle Royale Arena",
    description: "Last player standing wins! Drop into the arena, find weapons, and eliminate opponents.",
    thumbnail: "battle",
    category: "Action",
    players: 5678,
    maxPlayers: 100,
    rating: 4.6,
    creator: "ArenaKing",
    tags: ["battle-royale", "shooter", "pvp"],
    featured: true,
  },
  {
    id: "g7",
    title: "Pet Simulator X",
    description: "Collect and raise adorable pets! Trade with friends and discover rare creatures.",
    thumbnail: "pets",
    category: "Simulation",
    players: 4321,
    maxPlayers: 25,
    rating: 4.4,
    creator: "PetLover",
    tags: ["pets", "collecting", "trading"],
  },
  {
    id: "g8",
    title: "Murder Mystery",
    description: "One player is the killer, one is the sheriff. Can you figure out who is who before it is too late?",
    thumbnail: "mystery",
    category: "Social",
    players: 987,
    maxPlayers: 12,
    rating: 4.2,
    creator: "MysteryMind",
    tags: ["mystery", "social", "detective"],
  },
  {
    id: "g9",
    title: "Build & Create",
    description: "Unleash your creativity! Build anything you can imagine in this sandbox world.",
    thumbnail: "build",
    category: "Sandbox",
    players: 2345,
    maxPlayers: 40,
    rating: 4.7,
    creator: "CreativeStudio",
    tags: ["sandbox", "building", "creative"],
  },
  {
    id: "g10",
    title: "Ninja Legends",
    description: "Train to become the ultimate ninja! Unlock powerful abilities and defeat bosses.",
    thumbnail: "ninja",
    category: "RPG",
    players: 1890,
    maxPlayers: 15,
    rating: 4.5,
    creator: "NinjaForge",
    tags: ["rpg", "ninja", "action", "adventure"],
  },
  {
    id: "g11",
    title: "Escape Room",
    description: "Solve puzzles and escape the room before time runs out! Work with friends or go solo.",
    thumbnail: "escape",
    category: "Puzzle",
    players: 654,
    maxPlayers: 6,
    rating: 4.1,
    creator: "PuzzlePro",
    tags: ["puzzle", "escape", "coop"],
  },
  {
    id: "g12",
    title: "Fashion Show",
    description: "Design outfits, walk the runway, and vote for the best looks! Express your style.",
    thumbnail: "fashion",
    category: "Social",
    players: 1234,
    maxPlayers: 20,
    rating: 4.0,
    creator: "FashionStar",
    tags: ["fashion", "social", "creative"],
  },
];

export const friends: Friend[] = [
  { id: "f1", username: "ProGamer99", avatar: "avatar1", status: "online", currentGame: "HNPP Obby Challenge" },
  { id: "f2", username: "NightOwl", avatar: "avatar2", status: "in-game", currentGame: "Zombie Survival" },
  { id: "f3", username: "StarPlayer", avatar: "avatar3", status: "online" },
  { id: "f4", username: "CoolKid2024", avatar: "avatar4", status: "idle" },
  { id: "f5", username: "GameWizard", avatar: "avatar5", status: "offline", lastSeen: "2 hours ago" },
  { id: "f6", username: "PixelMaster", avatar: "avatar6", status: "online", currentGame: "Build & Create" },
  { id: "f7", username: "ShadowNinja", avatar: "avatar7", status: "in-game", currentGame: "Ninja Legends" },
  { id: "f8", username: "RocketRacer", avatar: "avatar8", status: "offline", lastSeen: "1 day ago" },
  { id: "f9", username: "DiamondQueen", avatar: "avatar9", status: "online" },
  { id: "f10", username: "ThunderBolt", avatar: "avatar10", status: "idle" },
  { id: "f11", username: "CosmicWolf", avatar: "avatar11", status: "offline", lastSeen: "3 hours ago" },
  { id: "f12", username: "BlazeFire", avatar: "avatar12", status: "online", currentGame: "Battle Royale Arena" },
];

export const categories = [
  "All",
  "Adventure",
  "Action",
  "Strategy",
  "Racing",
  "Simulation",
  "Social",
  "RPG",
  "Puzzle",
  "Sandbox",
];

export const gameColors: Record<string, string> = {
  obby: "from-green-500 to-emerald-700",
  tower: "from-blue-500 to-indigo-700",
  racing: "from-red-500 to-orange-700",
  zombie: "from-gray-600 to-red-900",
  tycoon: "from-yellow-400 to-amber-700",
  battle: "from-purple-500 to-pink-700",
  pets: "from-pink-400 to-rose-600",
  mystery: "from-slate-600 to-slate-900",
  build: "from-cyan-400 to-blue-600",
  ninja: "from-violet-500 to-purple-900",
  escape: "from-amber-500 to-orange-800",
  fashion: "from-fuchsia-400 to-pink-700",
};

export const avatarColors: Record<string, string> = {
  avatar1: "bg-red-500",
  avatar2: "bg-blue-500",
  avatar3: "bg-green-500",
  avatar4: "bg-yellow-500",
  avatar5: "bg-purple-500",
  avatar6: "bg-pink-500",
  avatar7: "bg-indigo-500",
  avatar8: "bg-orange-500",
  avatar9: "bg-cyan-500",
  avatar10: "bg-teal-500",
  avatar11: "bg-gray-500",
  avatar12: "bg-rose-500",
};
